python_library(
  name = 'net',
  sources = rglobs('*.py'),
  dependencies = [
    'src/python/twitter/common/dirutil',
    'src/python/twitter/common/lang',
    'src/python/twitter/common/quantity',
    '3rdparty/python:requests',
  ],
)
