python_library(
  name = 'cache',
  sources = globs('*.py'),
  dependencies = [
    'src/python/twitter/common/contextutil',
    'src/python/twitter/common/dirutil',
    'src/python/twitter/common/quantity',
  ]
)
