python_library(
  name = 'ivy',
  sources = globs('*.py'),
  dependencies = [
    'src/python/twitter/common/collections',
    'src/python/twitter/common/contextutil',
    'src/python/twitter/common/dirutil',
    'src/python/twitter/common/lang',
    'src/python/twitter/common/log',
    'src/python/twitter/common/quantity',
    'src/python/twitter/pants/base:config',
    'src/python/twitter/pants/java:executor',
    'src/python/twitter/pants/java:util',
    'src/python/twitter/pants/net',
  ]
)
