# Copyright 2014 Pants project contributors (see CONTRIBUTORS.md).
# Licensed under the Apache License, Version 2.0 (see LICENSE).

python_library(
  name = 'ivy',
  sources = globs('*.py'),
  dependencies = [
    'src/python/pants/BUILD.commons:twitter.common.collections',
    'src/python/pants/BUILD.commons:twitter.common.contextutil',
    'src/python/pants/BUILD.commons:twitter.common.dirutil',
    'src/python/pants/BUILD.commons:twitter.common.lang',
    'src/python/pants/BUILD.commons:twitter.common.log',
    'src/python/pants/BUILD.commons:twitter.common.quantity',
    'src/python/pants/base:config',
    'src/python/pants/java:executor',
    'src/python/pants/java:util',
    'src/python/pants/net',
  ]
)
