python_library(
  name = 'fs',
  sources = globs('*.py'),
  dependencies = [
    'src/python/twitter/common/collections',
    'src/python/twitter/common/contextutil',
    'src/python/twitter/common/lang',
  ]
)
